openapi: 3.0.3
info:
  title: Spec in YAML
  description: Spec in YAML
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/'
  - url: 'http://test.awesome.com/'
  - url: 'http://awesome.com/'

paths:
  /ping:
    get:
      tags:
        - system
      responses:
        200:
          description: "Ping"
          content:
            plain/text:
              schema:
                type: string
